version: '3.8'

services:
  wordpress:
    container_name: soul-travel-wordpress
    image: wordpress:latest
    depends_on:
      - db
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      # main
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins

      # temp
      - ./temp/cli-cache:/.wp-cli/cache
      - ./temp/wp-upgrade:/var/www/html/wp-content/upgrade
      - ./temp/wp-upgrade-backup:/var/www/html/wp-content/upgrade-temp-backup
      - ./temp/wp-uploads:/var/www/html/wp-content/uploads
      - ./temp/wp-lang:/var/www/html/wp-content/languages
      - ./temp/wp-lang-plugins:/var/www/html/wp-content/languages/plugins
  db:
    image: mariadb:latest
    container_name: soul-travel-db
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - ./.env

  phpmyadmin:
    container_name: soul-travel-phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
