version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: wp-db
    volumes:
      - ./data:/var/lib/mysql
    env_file: .env
    restart: unless-stopped

  wordpress:
    image: wordpress:latest
    container_name: wp-app
    depends_on:
      - db
    ports:
      - "3000:80"
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
    env_file: .env
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp-phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    restart: unless-stopped
